server:
  port: 8091

eureka:
  client:
    serviceUrl: #注册中心的注册地址
      defaultZone: http://192.168.1.103:8090/eureka/
    registry-fetch-interval-seconds: 5 #指示从eureka获取注册表信息的频率(以秒为单位)
    register-with-eureka: true
    fetch-registry: true
  instance:
    #    instance-id: ${spring.application.instance_id:${random.value}}:${spring.application.name}:${server.port}
    prefer-ip-address: true # 就把ip注册到eureka了，不加的话我看过eureka注册界面，是以docker容器的container id注册过去的
    lease-renewal-interval-in-seconds: 3 #表示eureka客户端发送心跳的频率(以秒为单位)
    lease-expiration-duration-in-seconds: 5  # 过期时间，默认90s, 可不配置

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
          lowerCaseServiceId: true #w微服务名称小写呈现
      routes:
        - id: gn-web
          uri: lb://gn-web #路由到的服务
          predicates:
            - Path=/web/**  #匹配到的路径
          filters:
            - StripPrefix=1

        - id: gn-gds
          uri: lb://gn-gds
          predicates:
            - Path=/gds/**
          filters:
            - StripPrefix=1

        - id: gn-api
          uri: lb://gn-api
          predicates:
            - Path=/api/**
#          filters:
#            - StripPrefix=1

        - id: gn-mp
          uri: lb://gn-mp
          predicates:
            - Path=/mp/**
          filters:
            - StripPrefix=1